In [6]:
import numpy as np
import pandas as pd

np.random.seed(42)

# Generate 3 random 3x3 matrices from -10 to 10
matrices = []
for i in range(3):
    M = np.random.randint(-10, 11, size=(3, 3))
    matrices.append(M)
    print(f"Matrix {i+1}:")
    print("Original Matrix")
    print(M)
    print()

# Generate determinant for each matrix
    det = np.linalg.det(M)
    print(f"Determinant: {det:.4f}")
    print()
    
    if abs(det) > 0.0001:
        inv_M = np.linalg.inv(M)
        print("Inverse of Matrix:")
        print(inv_M)
        print()
        
        product = M @ inv_M
        print("Verification (M × inverse_Matrix):")
        print(np.round(product, 10))
        print()
    else:
        print("Does not have inverse")

Matrix 1:
Original Matrix
[[-4  9  4]
 [ 0 -3 10]
 [-4  8  0]]

Determinant: -88.0000

Inverse of Matrix:
[[ 0.90909091 -0.36363636 -1.15909091]
 [ 0.45454545 -0.18181818 -0.45454545]
 [ 0.13636364  0.04545455 -0.13636364]]

Verification (M × inverse_Matrix):
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0.  0.  1.]]

Matrix 2:
Original Matrix
[[ 0 10 -7]
 [-3 -8 10]
 [-9  1 -5]]

Determinant: -525.0000

Inverse of Matrix:
[[-0.05714286 -0.08190476 -0.08380952]
 [ 0.2         0.12       -0.04      ]
 [ 0.14285714  0.17142857 -0.05714286]]

Verification (M × inverse_Matrix):
[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]

Matrix 3:
Original Matrix
[[ -9  10 -10]
 [  1   1   6]
 [ -1   5   4]]

Determinant: 74.0000

Inverse of Matrix:
[[-0.35135135 -1.21621622  0.94594595]
 [-0.13513514 -0.62162162  0.59459459]
 [ 0.08108108  0.47297297 -0.25675676]]

Verification (M × inverse_Matrix):
[[ 1. -0.  0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]



In [7]:
# Question 5: Average, variance, and correlation
# Load data
df = pd.read_csv('kc_house_data.csv')

# Remove id, date, zipcode
df = df.drop(columns=['id', 'date', 'zipcode'])

# Select feature but price
features = [col for col in df.columns if col != 'price']

# Part 1: Compute statistics
stats = df[features].agg(['mean', 'min', 'max', 'var']).T.round(3)

# Results
print("PART 1: Statistics")
print(stats)
print(f"\nHighest average feature:{stats['mean'].idxmax()} ({stats['mean'].max()})")
print(f"Lowest average feature:{stats['mean'].idxmin()} ({stats['mean'].min()})")
print(f"Highest variance feature:{stats['var'].idxmax()} ({stats['var'].max()})")
print(f"Lowest variance feature:{stats['var'].idxmin()}({stats['var'].min()})")

PART 1: Statistics
                    mean       min          max           var
bedrooms           3.371     0.000       33.000  8.650000e-01
bathrooms          2.115     0.000        8.000  5.930000e-01
sqft_living     2079.900   290.000    13540.000  8.435337e+05
sqft_lot       15106.968   520.000  1651359.000  1.715659e+09
floors             1.494     1.000        3.500  2.920000e-01
waterfront         0.008     0.000        1.000  7.000000e-03
view               0.234     0.000        4.000  5.870000e-01
condition          3.409     1.000        5.000  4.230000e-01
grade              7.657     1.000       13.000  1.382000e+00
sqft_above      1788.391   290.000     9410.000  6.857347e+05
sqft_basement    291.509     0.000     4820.000  1.958727e+05
yr_built        1971.005  1900.000     2015.000  8.627970e+02
yr_renovated      84.402     0.000     2015.000  1.613462e+05
lat               47.560    47.156       47.778  1.900000e-02
long            -122.214  -122.519     -121.315  2.

In [8]:
# Part 2: Correlation with price
corr = df[features].corrwith(df['price']).round(3).sort_values(ascending=False)

# Results
print(f"\nPART 2: Correlation with Price\n")
print(corr)

# Filter only positive correlations
positive_corr = corr[corr > 0]

# List them
print(f"\nFeatures: {list(positive_corr.index)}")

# Highest positive correlation
print(f"Highest positive correlation: {corr.idxmax()} ({corr.max()})")


PART 2: Correlation with Price

sqft_living      0.702
grade            0.667
sqft_above       0.606
sqft_living15    0.585
bathrooms        0.525
view             0.397
sqft_basement    0.324
bedrooms         0.308
lat              0.307
waterfront       0.266
floors           0.257
yr_renovated     0.126
sqft_lot         0.090
sqft_lot15       0.082
yr_built         0.054
condition        0.036
long             0.022
dtype: float64

Features: ['sqft_living', 'grade', 'sqft_above', 'sqft_living15', 'bathrooms', 'view', 'sqft_basement', 'bedrooms', 'lat', 'waterfront', 'floors', 'yr_renovated', 'sqft_lot', 'sqft_lot15', 'yr_built', 'condition', 'long']
Highest positive correlation: sqft_living (0.702)


In [9]:
# Part 3: Negative correlations
negative_corr = corr[corr < 0]
print(f"\nPART 3: Negative Correlations")
print(f"Number of negative correlations: {len(negative_corr)}")


PART 3: Negative Correlations
Number of negative correlations: 0
