In [49]:
import numpy as np

# Set seed for reproducibility (optional)
np.random.seed(42)

# Generate 3 random 3x3 matrices with integers from -10 to 10
matrices = []
for i in range(3):
    M = np.random.randint(-10, 11, size=(3, 3))
    matrices.append(M)
    print(f"Matrix {i+1}:")
    print("Original Matrix")
    print(M)
    print

    det = np.linalg.det(M)
    print(f"Determinant: {det:.4f}")
    print()
    
    if abs(det) > 0.0001:
        inv_M = np.linalg.inv(M)
        print("Inverse of Matrix:")
        print(inv_M)
        print()
        
        product = M @ inv_M
        print("Verification (M × inverse_Matrix):")
        print(np.round(product, 10))
        print()
    else:
        print("This matrix is SINGULAR - No inverse exists!")
        print()

Matrix 1:
Original Matrix
[[-4  9  4]
 [ 0 -3 10]
 [-4  8  0]]
Determinant: -88.0000

Inverse of Matrix:
[[ 0.90909091 -0.36363636 -1.15909091]
 [ 0.45454545 -0.18181818 -0.45454545]
 [ 0.13636364  0.04545455 -0.13636364]]

Verification (M × inverse_Matrix):
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [-0.  0.  1.]]

Matrix 2:
Original Matrix
[[ 0 10 -7]
 [-3 -8 10]
 [-9  1 -5]]
Determinant: -525.0000

Inverse of Matrix:
[[-0.05714286 -0.08190476 -0.08380952]
 [ 0.2         0.12       -0.04      ]
 [ 0.14285714  0.17142857 -0.05714286]]

Verification (M × inverse_Matrix):
[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]

Matrix 3:
Original Matrix
[[ -9  10 -10]
 [  1   1   6]
 [ -1   5   4]]
Determinant: 74.0000

Inverse of Matrix:
[[-0.35135135 -1.21621622  0.94594595]
 [-0.13513514 -0.62162162  0.59459459]
 [ 0.08108108  0.47297297 -0.25675676]]

Verification (M × inverse_Matrix):
[[ 1. -0.  0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]



In [52]:
import pandas as pd
import numpy as np

# Load data
df = pd.read_csv('kc_house_data.csv')

# Remove id, date, zipcode
df = df.drop(columns=['id', 'date', 'zipcode'])

# Separate features and response
features = [col for col in df.columns if col != 'price']

# Part 1: Compute statistics
stats = df[features].agg(['mean', 'min', 'max', 'var']).T
stats.columns = ['Average', 'Min', 'Max', 'Variance']

# Part 2: Correlation with price
corr = df[features].corrwith(df['price']).sort_values(ascending=False)

# Display results
print("PART 1: Statistics")
print(stats)
print("\nPART 2: Correlation with Price")
print(corr)

PART 1: Statistics
                    Average        Min           Max      Variance
bedrooms           3.370842     0.0000  3.300000e+01  8.650150e-01
bathrooms          2.114757     0.0000  8.000000e+00  5.931513e-01
sqft_living     2079.899736   290.0000  1.354000e+04  8.435337e+05
sqft_lot       15106.967566   520.0000  1.651359e+06  1.715659e+09
floors             1.494309     1.0000  3.500000e+00  2.915880e-01
waterfront         0.007542     0.0000  1.000000e+00  7.485226e-03
view               0.234303     0.0000  4.000000e+00  5.872426e-01
condition          3.409430     1.0000  5.000000e+00  4.234665e-01
grade              7.656873     1.0000  1.300000e+01  1.381703e+00
sqft_above      1788.390691   290.0000  9.410000e+03  6.857347e+05
sqft_basement    291.509045     0.0000  4.820000e+03  1.958727e+05
yr_built        1971.005136  1900.0000  2.015000e+03  8.627973e+02
yr_renovated      84.402258     0.0000  2.015000e+03  1.613462e+05
lat               47.560053    47.1559  4.7

In [53]:
# Load data
df = pd.read_csv('kc_house_data.csv')

# Remove id, date, zipcode
df = df.drop(columns=['id', 'date', 'zipcode'])
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,47.5112,-122.257,1340,5650
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,47.7210,-122.319,1690,7639
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,47.7379,-122.233,2720,8062
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,47.5208,-122.393,1360,5000
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,47.6993,-122.346,1530,1509
21609,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,47.5107,-122.362,1830,7200
21610,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,47.5944,-122.299,1020,2007
21611,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,47.5345,-122.069,1410,1287
